/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConfigRouteImport } from './routes/api-config'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelRouteImport } from './routes/model'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApiPublicDetectRouteImport } from './routes/api/public/detect'
import { Route as ApiPublicModelsRouteImport } from './routes/api/public/models'
import { Route as ApiPublicDetectAudioRouteImport } from './routes/api/public/detect.audio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api-config',
  path: '/api-config',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDetectRoute = ApiPublicDetectRouteImport.update({
  id: '/api/public/detect',
  path: '/api/public/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicModelsRoute = ApiPublicModelsRouteImport.update({
  id: '/api/public/models',
  path: '/api/public/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDetectAudioRoute = ApiPublicDetectAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => ApiPublicDetectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-config': typeof ApiConfigRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/model': typeof ModelRoute
  '/profile': typeof ProfileRoute
  '/api/public/detect': typeof ApiPublicDetectRouteWithChildren
  '/api/public/models': typeof ApiPublicModelsRoute
  '/api/public/detect/audio': typeof ApiPublicDetectAudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-config': typeof ApiConfigRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/model': typeof ModelRoute
  '/profile': typeof ProfileRoute
  '/api/public/detect': typeof ApiPublicDetectRouteWithChildren
  '/api/public/models': typeof ApiPublicModelsRoute
  '/api/public/detect/audio': typeof ApiPublicDetectAudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-config': typeof ApiConfigRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/model': typeof ModelRoute
  '/profile': typeof ProfileRoute
  '/api/public/detect': typeof ApiPublicDetectRouteWithChildren
  '/api/public/models': typeof ApiPublicModelsRoute
  '/api/public/detect/audio': typeof ApiPublicDetectAudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-config'
    | '/history'
    | '/login'
    | '/model'
    | '/profile'
    | '/api/public/detect'
    | '/api/public/models'
    | '/api/public/detect/audio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-config'
    | '/history'
    | '/login'
    | '/model'
    | '/profile'
    | '/api/public/detect'
    | '/api/public/models'
    | '/api/public/detect/audio'
  id:
    | '__root__'
    | '/'
    | '/api-config'
    | '/history'
    | '/login'
    | '/model'
    | '/profile'
    | '/api/public/detect'
    | '/api/public/models'
    | '/api/public/detect/audio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConfigRoute: typeof ApiConfigRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ModelRoute: typeof ModelRoute
  ProfileRoute: typeof ProfileRoute
  ApiPublicDetectRoute: typeof ApiPublicDetectRouteWithChildren
  ApiPublicModelsRoute: typeof ApiPublicModelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-config': {
      id: '/api-config'
      path: '/api-config'
      fullPath: '/api-config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/detect': {
      id: '/api/public/detect'
      path: '/api/public/detect'
      fullPath: '/api/public/detect'
      preLoaderRoute: typeof ApiPublicDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/models': {
      id: '/api/public/models'
      path: '/api/public/models'
      fullPath: '/api/public/models'
      preLoaderRoute: typeof ApiPublicModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/detect/audio': {
      id: '/api/public/detect/audio'
      path: '/audio'
      fullPath: '/api/public/detect/audio'
      preLoaderRoute: typeof ApiPublicDetectAudioRouteImport
      parentRoute: typeof ApiPublicDetectRoute
    }
  }
}

interface ApiPublicDetectRouteChildren {
  ApiPublicDetectAudioRoute: typeof ApiPublicDetectAudioRoute
}

const ApiPublicDetectRouteChildren: ApiPublicDetectRouteChildren = {
  ApiPublicDetectAudioRoute: ApiPublicDetectAudioRoute,
}

const ApiPublicDetectRouteWithChildren = ApiPublicDetectRoute._addFileChildren(
  ApiPublicDetectRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConfigRoute: ApiConfigRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ModelRoute: ModelRoute,
  ProfileRoute: ProfileRoute,
  ApiPublicDetectRoute: ApiPublicDetectRouteWithChildren,
  ApiPublicModelsRoute: ApiPublicModelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
